tickets = [
    {id: 1,
            passengerName:  "yassine",
            IdTrip: 1,
            seatNumber: 1 ,
            price: 25},
    {id: 2,
            passengerName: "said",
            IdTrip: 1,
            seatNumber: 2 ,
            price: 25},
    {id: 3,
            passengerName: "aymane",
            IdTrip: 7,
            seatNumber: 1 ,
            price: 150},
    {id: 4,
            passengerName: "karim",
            IdTrip: 7,
            seatNumber: 2 ,
            price: 150},
    {id: 5,
            passengerName: "salma",
            IdTrip: 7,
            seatNumber: 3 ,
            price: 150},
    {id: 6,
            passengerName: "morad",
            IdTrip: 1,
            seatNumber: 3 ,
            price: 25}]
